<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-vinimendes123/blob/main/Pr%C3%A1ticas_Devops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fáceis

In [ ]:
import numpy as np

rng = np.random.default_rng(42)

In [ ]:
v1 = np.zeros(10)
print(v1, v1.dtype, v1.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64 (10,)


In [ ]:
v2 = np.ones(10, dtype=np.float64)
print(v2, v2.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [ ]:
v3 = np.arange(10)
print(v3)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
A4 = np.arange(9).reshape(3,3)
print(A4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
v5 = np.array([1,2,0,0,4,0])
idx5 = np.nonzero(v5)[0]
print(idx5)

[0 1 4]


In [ ]:
v6 = np.linspace(0,1,12)
print(v6)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [ ]:
I7 = np.eye(5)
print(I7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
A8 = rng.random((3,3,3))
print(A8)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


In [ ]:
A9 = rng.random((10,10))
print(A9.min(), A9.max())

0.007362269751005512 0.9691763773477239


In [ ]:
x10 = np.array([1,2,3,4,5], dtype=float)
x10_norm = (x10 - x10.mean())/x10.std()
print(x10_norm)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
x11 = np.array([1,2,3], dtype=np.int32).astype(np.float32).astype(np.int64)
print(x11, x11.dtype)

[1 2 3] int64


In [ ]:
a12 = np.array([2,5,7,1,9])
a12_clip = np.clip(a12, 0, 5)
print(a12_clip)

[2 5 5 1 5]


In [ ]:
v13 = np.arange(10)
v13_inv = np.flip(v13)
print(v13_inv)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
a14 = np.array([1,2,3])
b14 = np.array([4,5,6])
hstack14 = np.hstack([a14,b14])
vstack14 = np.vstack([a14,b14])
print(hstack14)
print(vstack14)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
A15 = np.diag([5]*4)
print(A15)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [ ]:
A16 = np.arange(12).reshape(3,4)
print(A16.sum(axis=0))
print(A16.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [ ]:
v17 = rng.integers(0,10,100)
freq17 = np.bincount(v17, minlength=10)
print(freq17)

[ 7 13 13  9 11 13 10  5  6 13]


In [ ]:
v18 = np.arange(20)
sel18 = v18[1::3]
print(sel18)


[ 1  4  7 10 13 16 19]


In [ ]:
v19 = np.arange(20)
mask19 = v19%2==0
print(v19[mask19])

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
lst20 = [[1,2,3],[4,5,6]]
arr20 = np.array(lst20)
print(arr20, arr20.shape, arr20.dtype)

[[1 2 3]
 [4 5 6]] (2, 3) int64


In [ ]:
dates21 = np.arange(np.datetime64('2025-01-01'), np.datetime64('2025-01-08'))
print(dates21)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


In [ ]:
A22 = np.array([[1.,2.,3.],[4.,5.,6.]])
A22_centered = A22 - A22.mean(axis=0)
print(A22_centered)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [ ]:
a23 = np.array([1,2,3])
b23 = np.array([4,5,6])
elem_prod23 = a23*b23
dot_prod23 = a23 @ b23
print(elem_prod23, dot_prod23)

[ 4 10 18] 32


In [ ]:
A24 = np.arange(12).reshape(3,4)
A24[:,[0,2]] = A24[:,[2,0]]
print(A24)

[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


# Médios

In [ ]:
A25 = np.arange(9).reshape(3,3)
flat = A25.flatten()
rav = A25.ravel()
rav[0] = 99
print("A25:\n", A25)
print("flatten (cópia):", flat)

A25:
 [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]
flatten (cópia): [0 1 2 3 4 5 6 7 8]


In [ ]:
A26 = np.zeros((8,8), dtype=int)
A26[1::2, ::2] = 1
A26[::2, 1::2] = 1
print(A26)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x27 = np.arange(-5,6)
y27 = np.where(x27 < 0, 0, x27)
print(y27)

[0 0 0 0 0 0 1 2 3 4 5]


In [ ]:
v28 = rng.random(1_000_000)
mean28 = v28.mean()
err28 = abs(mean28 - 0.5)
print("Média:", mean28, "Erro absoluto:", err28)

Média: 0.49980731176580057 Erro absoluto: 0.00019268823419943404


In [ ]:
a29 = np.array([1,2,3])[:,None]
b29 = np.array([10,20,30,40])
sumas29 = a29 + b29
print(sumas29)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [ ]:
s30 = np.array([1,2,3,4,5])
k30 = np.array([2,1])
slices30 = np.lib.stride_tricks.sliding_window_view(s30, k30.size)
conv30 = (slices30 @ np.flip(k30))
print(conv30)

[ 5  8 11 14]


In [ ]:
A31 = rng.normal(size=(5,4))
mins = A31.min(axis=0)
maxs = A31.max(axis=0)
range_ = np.where(maxs != mins, maxs - mins, 1)
A31_norm = (A31 - mins) / range_
print(A31_norm)

[[0.         0.         1.         0.41313387]
 [0.79280353 0.54514049 0.61975483 0.21378068]
 [0.74526422 1.         0.88157697 0.        ]
 [1.         0.52847777 0.         1.        ]
 [0.26708366 0.07373189 0.75682388 0.25497525]]


In [ ]:
A32 = np.array([[3,9],[1,4],[2,5]])
A32_sorted = A32[A32[:,1].argsort()]
print(A32_sorted)

[[1 4]
 [2 5]
 [3 9]]


In [36]:
x33 = np.array([3,1,2,3,2,3,1])
u33, idx33, counts33 = np.unique(x33, return_index=True, return_counts=True)
print("Únicos:", u33)
print("Primeira ocorrência:", idx33)
print("Contagens:", counts33)

Únicos: [1 2 3]
Primeira ocorrência: [1 2 0]
Contagens: [2 2 3]


In [37]:
P34 = rng.random((5,2))
d2 = ((P34[:,None,:] - P34[None,:,:])**2).sum(axis=2)
D34 = np.sqrt(d2)
print(D34)

[[0.         0.60662871 0.54639411 0.42079762 0.08458608]
 [0.60662871 0.         0.65227148 0.67621534 0.56548922]
 [0.54639411 0.65227148 0.         0.15774482 0.46375412]
 [0.42079762 0.67621534 0.15774482 0.         0.34435127]
 [0.08458608 0.56548922 0.46375412 0.34435127 0.        ]]


In [38]:
A35 = rng.standard_normal((1000,3))
cov35 = np.cov(A35, rowvar=False)
corr35 = np.corrcoef(A35, rowvar=False)
print("Cov:\n", cov35)
print("Corr:\n", corr35)

Cov:
 [[ 0.97786566 -0.00923633 -0.01748112]
 [-0.00923633  1.01623999 -0.02659413]
 [-0.01748112 -0.02659413  1.08694138]]
Corr:
 [[ 1.         -0.00926534 -0.01695612]
 [-0.00926534  1.         -0.02530373]
 [-0.01695612 -0.02530373  1.        ]]


In [39]:
y36 = np.array([2,0,1,2])
onehot36 = np.eye(y36.max()+1)[y36]
print(onehot36)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Difíceis